name: app
description: sample flutter unity widget app with redux-ish state management.
publish_to: 'none'
version: 1.0.0+0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.0.3
  flutter_unity_widget_2: ^6000.0.0
  freezed_annotation: ^3.1.0
  hooks_riverpod: ^3.0.3
  logger: ^2.5.0
  riverpod_annotation: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  custom_lint: ^0.8.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
